openprocurement/auctions/core/traversal.py, openprocurement/auctions/core/validation.py
Added permissions for bot and change validator for changing status to "pre.enquiries"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/2)
=> Added new status "pre.enquiries"

openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/4)
=> Fix 500 Error in listing a421134621643366

buildout.cfg, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/tests/blanks/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/7)
=> Move tests from dgf and snitch function from registry

openprocurement/auctions/core/contracting/dgf/utils.py, openprocurement/auctions/core/contracting/dgf/views/contract.py, openprocurement/auctions/core/contracting/dgf/views/contract_document.py, openprocurement/auctions/core/contracting/flash/views/contract.py, openprocurement/auctions/core/contracting/flash/views/contract_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/10)
=> A506789162725440 separating contracting

.gitignore, .travis.yml, buildout.cfg, openprocurement/auctions/core/adapters.py, openprocurement/auctions/core/includeme.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/9)
=> add and register adapter

openprocurement/auctions/core/tests/auctions.py, openprocurement/auctions/core/tests/blanks/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/8)
=> Move test to blanks

openprocurement/auctions/core/tests/blanks/lot_blanks.py, openprocurement/auctions/core/tests/blanks/migration_blanks.py, openprocurement/auctions/core/tests/blanks/question_blanks.py, openprocurement/auctions/core/tests/blanks/tender_blanks.py, openprocurement/auctions/core/tests/lot.py, openprocurement/auctions/core/tests/question.py, openprocurement/auctions/core/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/15)
=> A507910391639580 tests refactoring

openprocurement/auctions/core/tests/auctions.py, openprocurement/auctions/core/tests/award.py, openprocurement/auctions/core/tests/blanks/auction_blanks.py, openprocurement/auctions/core/tests/blanks/award_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/16)
=> A510591380902399 add mixins

openprocurement/auctions/core/tests/blanks/bidder_blanks.py, openprocurement/auctions/core/tests/blanks/cancellation_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/18)
=> ADD common blanks for bidder; fixed bug in test

buildout.cfg, openprocurement/auctions/core/models.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/6)
=> Режим quick, опція no-auction

openprocurement/auctions/core/adapters.py, openprocurement/auctions/core/plugins/awarding_1_0/utils.py, openprocurement/auctions/core/plugins/awarding_1_0/views/award.py, openprocurement/auctions/core/plugins/awarding_2_0/utils.py, openprocurement/auctions/core/utils.py
depends on API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/13)
=> add utils to configurator

openprocurement/auctions/core/tests/bidder.py, openprocurement/auctions/core/tests/blanks/bidder_blanks.py, openprocurement/auctions/core/tests/blanks/cancellation_blanks.py, openprocurement/auctions/core/tests/blanks/chronograph_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/19)
=> Refactoring code

openprocurement/auctions/core/constants.py, openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/blanks/auction_blanks.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/20)
=> A224443466734796 no auction

openprocurement/auctions/core/plugins/awarding_1_0/views/award.py, openprocurement/auctions/core/plugins/awarding_1_0/views/award_complaint.py, openprocurement/auctions/core/plugins/awarding_1_0/views/award_complaint_document.py, openprocurement/auctions/core/plugins/awarding_1_0/views/award_document.py, openprocurement/auctions/core/plugins/awarding_2_0/views/award.py, openprocurement/auctions/core/plugins/awarding_2_0/views/award_complaint.py, openprocurement/auctions/core/plugins/awarding_2_0/views/award_complaint_document.py, openprocurement/auctions/core/plugins/awarding_2_0/views/award_document.py, openprocurement/auctions/core/plugins/contracting/dgf/models.py, openprocurement/auctions/core/plugins/contracting/flash/models.py
**Depends on [API PR](https://github.com/openprocurement/openprocurement.api/pull/255)**
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/22)
=> A507127548074095 awarding routing

openprocurement/auctions/core/plugins/awarding/v3/constants.py, openprocurement/auctions/core/plugins/awarding/v3/migration.py, openprocurement/auctions/core/plugins/awarding/v3/models.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py, openprocurement/auctions/core/plugins/awarding/v3/views/award_complaint.py, openprocurement/auctions/core/plugins/awarding/v3/views/award_complaint_document.py, openprocurement/auctions/core/plugins/awarding/v3/views/award_document.py, openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/plugins/contracting/v3/utils.py, openprocurement/auctions/core/plugins/contracting/v3/views/contract.py, openprocurement/auctions/core/plugins/contracting/v3/views/contract_document.py
Rename imports and predicates from v2 to v3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/28)
=> Copy contractings and awardings v2's to v3's

openprocurement/auctions/core/plugins/awarding/v2/constants.py, openprocurement/auctions/core/plugins/awarding/v2/utils.py, openprocurement/auctions/core/plugins/awarding/v3/constants.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/29)
=> add NUMBER_OF_BIDS_QUALIFIED constant

openprocurement/auctions/core/plugins/awarding/v3/models.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/30)
=> remove payment period, pending.payment status from award model

openprocurement/auctions/core/plugins/awarding/v1/models.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py, openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/plugins/contracting/v3/tests/validators.py, openprocurement/auctions/core/tests/blanks/award_blanks.py, openprocurement/auctions/core/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/31)
=> A519600399918109 add contracting fields

openprocurement/auctions/core/plugins/awarding/v1/adapters.py, openprocurement/auctions/core/plugins/awarding/v1/views/award.py, openprocurement/auctions/core/plugins/awarding/v2/adapters.py, openprocurement/auctions/core/plugins/awarding/v2/utils.py, openprocurement/auctions/core/plugins/awarding/v2/views/award.py, openprocurement/auctions/core/plugins/awarding/v3/adapters.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py, openprocurement/auctions/core/tests/blanks/award_blanks.py, openprocurement/auctions/core/utils.py
DEPENDS ON API PR https://github.com/openprocurement/openprocurement.api/pull/259
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/34)
=> add awarding configurators mixins

openprocurement/auctions/core/plugins/awarding/v1/models.py, openprocurement/auctions/core/plugins/awarding/v2/models.py, openprocurement/auctions/core/plugins/awarding/v3/models.py, openprocurement/auctions/core/plugins/contracting/v1/models.py, openprocurement/auctions/core/plugins/contracting/v2/models.py, openprocurement/auctions/core/plugins/contracting/v3/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/36)
=> use BaseAward and BaseContract from openprocurement.api

openprocurement/auctions/core/plugins/awarding/v2/adapters.py, openprocurement/auctions/core/plugins/awarding/v2/utils.py, openprocurement/auctions/core/plugins/awarding/v3/adapters.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/37)
=> add check_award_status method to adapter

openprocurement/auctions/core/adapters.py, openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/plugins/awarding/v1/adapters.py, openprocurement/auctions/core/plugins/awarding/v1/utils.py, openprocurement/auctions/core/plugins/awarding/v2/adapters.py, openprocurement/auctions/core/plugins/awarding/v2/utils.py, openprocurement/auctions/core/plugins/awarding/v3/adapters.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py
Depence on API https://github.com/openprocurement/openprocurement.api/pull/261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/41)
=> A532447786233334 next check adapter

openprocurement/auctions/core/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/42)
=> Use existed app in tests if it exists

openprocurement/auctions/core/plugins/awarding/v2/models.py, openprocurement/auctions/core/plugins/awarding/v2/tests/award.py, openprocurement/auctions/core/plugins/awarding/v3/migration.py, openprocurement/auctions/core/plugins/awarding/v3/models.py, openprocurement/auctions/core/plugins/awarding/v3/tests/blanks/migration_blanks.py, openprocurement/auctions/core/plugins/awarding/v3/tests/mgiration.py, openprocurement/auctions/core/plugins/awarding/v3/tests/migration.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/43)
=> A519704795287037 awardingv3 migration

openprocurement/auctions/core/plugins/contracting/v3/tests/validators.py, openprocurement/auctions/core/tests/auctions.py, openprocurement/auctions/core/tests/main.py, openprocurement/auctions/core/tests/tests.ini, setup.py
* Fix tests.ini configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/45)
=> Fix suite functions for tests

.gitignore, openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/plugins/contracting/v2/utils.py, openprocurement/auctions/core/plugins/contracting/v3/utils.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/46)
=> A568600982795170 style refactor

openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/plugins/awarding/includeme.py, openprocurement/auctions/core/plugins/awarding/v1/includeme.py, openprocurement/auctions/core/plugins/awarding/v2/includeme.py, openprocurement/auctions/core/plugins/awarding/v3/includeme.py, openprocurement/auctions/core/plugins/contracting/includeme.py, openprocurement/auctions/core/plugins/contracting/v1/includeme.py, openprocurement/auctions/core/plugins/contracting/v2/includeme.py, openprocurement/auctions/core/plugins/contracting/v3/includeme.py, openprocurement/auctions/core/utils.py
Add init_plugins functionality 
Add includeme functions on plugin and plugin version levels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/52)
=> A590830261032879_init_plugins

openprocurement/auctions/core/plugins/awarding/includeme.py, openprocurement/auctions/core/plugins/contracting/includeme.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/53)
=> Fix import statementes for awarding and contracting plugins

openprocurement/auctions/core/validation.py
**[DEPENDENCY on API](https://github.com/openprocurement/openprocurement.api/pull/266)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/55)
=> Move STATUS4ROLE

openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/contract_blanks.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/56)
=> A593255576070832 date paid bug

openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/contract_blanks.py, openprocurement/auctions/core/plugins/contracting/v3/tests/unit/contract_validation.py, openprocurement/auctions/core/tests/blanks/contract_blanks.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/58)
=> A594843395715728 document upload error

openprocurement/auctions/core/plugins/awarding/v3/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v3/views/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/59)
=> A595252539510038 change error message

openprocurement/auctions/core/plugins/awarding/v2_1/validators.py, openprocurement/auctions/core/tests/blanks/document_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/60)
=> Fix tests. Fix validator

openprocurement/auctions/core/plugins/awarding/v2_1/views/award.py, openprocurement/auctions/core/tests/blanks/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/62)
=> Fix import. Fix undefined variable

openprocurement/auctions/core/plugins/awarding/v2_1/tests/blanks/award_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/63)
=> Move tests from dgf awarding to plugins awarding blanks

openprocurement/auctions/core/constants.py, openprocurement/auctions/core/plugins/awarding/v2_1/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v2_1/validators.py, openprocurement/auctions/core/plugins/awarding/v2_1/views/award_document.py, openprocurement/auctions/core/plugins/contracting/v2_1/models.py, openprocurement/auctions/core/plugins/contracting/v2_1/tests/blanks/contract_blanks.py, openprocurement/auctions/core/plugins/contracting/v2_1/validators.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/66)
=> Fix tests. Use awarding type from configurator

openprocurement/auctions/core/plugins/awarding/v1/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v2_1/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v3/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/contracting/v2_1/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/blanks/cancellation_blanks.py, openprocurement/auctions/core/tests/blanks/complaint_blanks.py, openprocurement/auctions/core/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/blanks/lot_blanks.py, openprocurement/auctions/core/tests/blanks/question_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/68)
=> Use constant for renderer error

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/69)
=> Use proper import for DecimalType

openprocurement/auctions/core/plugins/contracting/v3/tests/unit/prolongation_manager.py, openprocurement/auctions/core/plugins/contracting/v3/utils/prolongation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/70)
=> Fix prolongation business days calc

openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/prolongation_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/71)
=> Fix prolongation tests

openprocurement/auctions/core/constants.py, openprocurement/auctions/core/plugins/awarding/v1/utils.py, openprocurement/auctions/core/plugins/awarding/v2/utils.py, openprocurement/auctions/core/plugins/awarding/v2_1/utils.py, openprocurement/auctions/core/plugins/awarding/v3/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/75)
=> Fix imports

openprocurement/auctions/core/plugins/awarding/v1/utils.py, openprocurement/auctions/core/plugins/awarding/v1/views/award_complaint.py, openprocurement/auctions/core/plugins/awarding/v2/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v3/tests/blanks/award_blanks.py, openprocurement/auctions/core/plugins/awarding/v3/tests/blanks/migration_blanks.py, openprocurement/auctions/core/plugins/contracting/v1/models.py, openprocurement/auctions/core/plugins/contracting/v1/views/contract.py, openprocurement/auctions/core/plugins/contracting/v2/views/contract.py, openprocurement/auctions/core/plugins/contracting/v2_1/models.py, openprocurement/auctions/core/plugins/contracting/v2_1/tests/blanks/contract_blanks.py, openprocurement/auctions/core/plugins/contracting/v2_1/views/contract.py, openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/chronograph_blanks.py, openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/contract_blanks.py, openprocurement/auctions/core/plugins/contracting/v3/tests/blanks/prolongation_blanks.py, openprocurement/auctions/core/plugins/contracting/v3/views/contract.py, openprocurement/auctions/core/plugins/contracting/v3/views/prolongation.py, openprocurement/auctions/core/tests/blanks/auction_blanks.py, openprocurement/auctions/core/tests/blanks/award_blanks.py, openprocurement/auctions/core/tests/blanks/chronograph_blanks.py, openprocurement/auctions/core/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/blanks/document_blanks.py, openprocurement/auctions/core/tests/blanks/lot_blanks.py, openprocurement/auctions/core/tests/blanks/tender_blanks.py, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/validation.py, openprocurement/auctions/core/views/auctions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/76)
=> Use imports from right module

openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/validation.py
Add forwarded imports from api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/78)
=> A622153013582226 api dependencies

openprocurement/auctions/core/plugins/awarding/v2_1/migration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/83)
=> Update 'migrate_awarding_1_0_to_awarding_2_1' migration function

openprocurement/auctions/core/events.py, openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/subscribers.py, openprocurement/auctions/core/utils.py
depends on https://github.com/openprocurement/openprocurement.api/pull/296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/84)
=>  Create subscriber for auction error handler 

openprocurement/auctions/core/plugins/contracting/v3/views/prolongation_document.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/prolongation_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/88)
=> Fix document can be added in applied status

openprocurement/auctions/core/models.py, openprocurement/auctions/core/plugins/awarding/v1/models.py, openprocurement/auctions/core/plugins/awarding/v2/models.py, openprocurement/auctions/core/plugins/awarding/v2_1/models.py, openprocurement/auctions/core/plugins/awarding/v3/models.py, openprocurement/auctions/core/plugins/contracting/v2/models.py, openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/tests/plugins/awarding/v3/tests/blanks/award_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/unit/contract_validation.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/unit/prolongation_manager.py
Change imports due to model refactoring
- https://github.com/openprocurement/openprocurement.api/pull/303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/89)
=> A657023234196457 model refactoring

openprocurement/auctions/core/plugins/awarding/v3/migration.py, openprocurement/auctions/core/plugins/contracting/v3/constants.py, openprocurement/auctions/core/plugins/contracting/v3/utils/prolongation.py, openprocurement/auctions/core/tests/plugins/awarding/v3/tests/blanks/migration_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/prolongation_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/unit/prolongation_manager.py
- https://github.com/openprocurement/openprocurement.api/pull/289
- https://github.com/openprocurement/openprocurement.api/pull/304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/81)
=> A634897126660620 signing period fixed hour

openprocurement/auctions/core/__init__.py, openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/tests/app_meta.yaml, openprocurement/auctions/core/tests/plugins.yaml, openprocurement/auctions/core/tests/tests.ini, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/91)
=> Order plugins

openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/prolongation_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/unit/prolongation_manager.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/94)
=> fix sandbox mod tests in dgf

openprocurement/auctions/core/traversal.py, openprocurement/auctions/core/views/auctions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/93)
=>  Use ApiResourceListing mixin 

openprocurement/auctions/core/models.py
- https://github.com/openprocurement/openprocurement.api/pull/314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/96)
=> A604204973640971 swiftsure procedure

openprocurement/auctions/core/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/100)
=> Move setUpDS to BaseWebTest

openprocurement/auctions/core/plugins/contracting/v3/models.py, openprocurement/auctions/core/tests/base.py
коротке рев'ю
.зробив так щоб була тільки одна спроба ініціалізації аплікації
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/99)
=> attepmt only once for initialization of app

openprocurement/auctions/core/plugins/awarding/base/adapters.py, openprocurement/auctions/core/plugins/awarding/base/interfaces.py, openprocurement/auctions/core/plugins/awarding/v1/adapters.py, openprocurement/auctions/core/plugins/awarding/v1/includeme.py, openprocurement/auctions/core/plugins/awarding/v1/interfaces.py, openprocurement/auctions/core/plugins/awarding/v1/models.py, openprocurement/auctions/core/plugins/awarding/v1/views/award.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/92)
=> Move views code to the adapter

openprocurement/auctions/core/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/fixtures/prolongation.py, openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/prolongation_blanks.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/103)
=> Fix tests with documentservice

openprocurement/auctions/core/plugins/awarding/v1/includeme.py, openprocurement/auctions/core/plugins/awarding/v1/views/award.py, openprocurement/auctions/core/plugins/awarding/v2/adapters.py, openprocurement/auctions/core/plugins/awarding/v2/includeme.py, openprocurement/auctions/core/plugins/awarding/v2/interfaces.py, openprocurement/auctions/core/plugins/awarding/v2/models.py, openprocurement/auctions/core/plugins/awarding/v2/views/award.py, openprocurement/auctions/core/plugins/awarding/v2_1/interfaces.py, openprocurement/auctions/core/plugins/awarding/v2_1/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/105)
=> A672645308678290 awarding v2 adapter

openprocurement/auctions/core/models.py, openprocurement/auctions/core/plugins/awarding/base/adapters.py, openprocurement/auctions/core/plugins/awarding/v1/adapters.py, openprocurement/auctions/core/plugins/awarding/v2_1/adapters.py, openprocurement/auctions/core/plugins/awarding/v2_1/includeme.py, openprocurement/auctions/core/plugins/awarding/v2_1/views/award.py, openprocurement/auctions/core/tests/plugins/awarding/v2_1/tests/blanks/award_blanks.py
- Remove obsolete docstrings
- Update tests_blanks on award
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/107)
=> Move logic from view to the adapter

openprocurement/auctions/core/models.py
Косметичні правки по стилю.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/110)
=> Fix style in the Contract model validators

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/111)
=> Add extras_require

openprocurement/auctions/core/models.py, openprocurement/auctions/core/validation.py
add arg container to validate document
fix code issues in changed files
add doc type for models
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/109)
=> add arg container for validate data

openprocurement/auctions/core/traversal.py, openprocurement/auctions/core/validation.py, openprocurement/auctions/core/views/mixins.py
* Add access for auction creation for concierge
* Fix accreditation level validation
* Remove transfer_token support for bid object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/115)
=> A604204973640971 swiftsure procedure accreditation

openprocurement/auctions/core/includeme.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/116)
=> Use proper argument for get_plugin_aliases

openprocurement/auctions/core/includeme.py
**Depends on** https://github.com/openprocurement/openprocurement.api/pull/334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/118)
=> Change plugin_map argument for the get_plugin_aliases function

openprocurement/auctions/core/models.py, openprocurement/auctions/core/plugins/transferring/includeme.py, openprocurement/auctions/core/plugins/transferring/models.py, openprocurement/auctions/core/plugins/transferring/traversal.py, openprocurement/auctions/core/plugins/transferring/utils.py, openprocurement/auctions/core/plugins/transferring/validation.py, openprocurement/auctions/core/plugins/transferring/views/auction.py, openprocurement/auctions/core/plugins/transferring/views/transfer.py, openprocurement/auctions/core/tests/app_meta.yaml, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/tests/plugins/transferring/blanks/resource_blanks.py, openprocurement/auctions/core/tests/plugins/transferring/main.py, openprocurement/auctions/core/tests/plugins/transferring/mixins.py, openprocurement/auctions/core/tests/plugins/transferring/transfer.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/117)
=> add transferring

openprocurement/auctions/core/plugins/awarding/v3_1/models.py, openprocurement/auctions/core/plugins/awarding/v3_1/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/122)
=> Change admissionPeriod.endDate generation for awarding 3.1

openprocurement/auctions/core/tests/plugins/contracting/v3/tests/blanks/prolongation_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/123)
=> add mock auction for test of prolongations

openprocurement/auctions/core/models.py
- https://github.com/openprocurement/openprocurement.api/pull/344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/125)
=> A699496854206332 reg details

openprocurement/auctions/core/plugins/awarding/v3_1/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/126)
=> Change dgfItem to SwiftsureItem in 3.1 awarding

openprocurement/auctions/core/plugins/contracting/v3_1/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/127)
=> Change dgfItem to SwiftsureItem for 3.1 contract

openprocurement/auctions/core/tests/plugins/transferring/blanks/resource_blanks.py
Add test for auction created by concierge
- https://github.com/openprocurement/openprocurement.api/pull/348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/128)
=> A701212988669838 transfer token from request

openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/129)
=> Extract accreditation validation logic

openprocurement/auctions/core/validation.py
Update call of accreditation validation functions
* Add resource_type as argument to function for proper error
message formatting
- https://github.com/openprocurement/openprocurement.api/pull/356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/130)
=> A707082877755959 accr validation err msg

openprocurement/auctions/core/models.py, openprocurement/auctions/core/traversal.py
- Add permission for concierge to edit auction
- Add role for model serializing in 'pending.activation' status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/131)
=> A645161816362812 pending activation

openprocurement/auctions/core/models.py
Add forwarded import for ContactPoint model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/132)
=> A710839966323293 additional contact points

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/133)
=> Remove validation for lot documents in swiftsureDocument

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/134)
=> Remove possibility to patch any field in active.tendering status

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/135)
=> Add cancellationDetails

openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/plugins/transferring/blanks/resource_blanks.py
* Update transferring test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/136)
=> Update create role for swiftsure auction

openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/139)
=> Roles for tessel

openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/140)
=> Delete by admin

openprocurement/auctions/core/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/141)
=> Remove unused imports

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/142)
=> Adaptate validator

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/143)
=> Remove status from blacklist in create role

openprocurement/auctions/core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/144)
=> Add ContractTerms model

openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/145)
=> Fix unsuccessful auction status

openprocurement/auctions/core/constants.py, openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/147)
=> Validate x platform legal details

openprocurement/auctions/core/plugins/contracting/v3_1/adapters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/149)
=> Fix create_validators tuple for contracting v3.1 adapter

openprocurement/auctions/core/models/__init__.py, openprocurement/auctions/core/models/roles.py, openprocurement/auctions/core/models/schema.py
1. Turn `models.py` into `models` module, consisting of `schema.py` `validators.py` `roles.py`.
2. Extract roles from models file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/155)
=> Models module refactor

openprocurement/auctions/core/models.py, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/tests/blanks/auction_blanks.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/151)
=> koatuu_additional_classification

openprocurement/auctions/core/models/roles.py, openprocurement/auctions/core/models/schema.py
- Move `sensitive_embedded_role`
- Sort roles
- Make swiftsure roles independent from dgf ones
- Make tessel roles independend from dgf
- Defragment swifsure roles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/156)
=> Deep roles refactor

openprocurement/auctions/core/models/schema.py, openprocurement/auctions/core/tests/fixtures/items.py, openprocurement/auctions/core/tests/models.py
to 4 decimal places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/158)
=> Set precision of SwiftsureItem.quantity

openprocurement/auctions/core/models/roles.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/161)
=> Add `rectificationPeriod` to the dgf/create role

openprocurement/auctions/core/includeme.py, openprocurement/auctions/core/models/schema.py, openprocurement/auctions/core/plugins/transferring/validation.py, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/154)
=> rm level of accreditation from models

openprocurement/auctions/core/tests/auctions.py, openprocurement/auctions/core/tests/blanks/extract_credentials.py, openprocurement/auctions/core/tests/tender.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/166)
=> Tests for extract credentials

openprocurement/auctions/core/models/schema.py, openprocurement/auctions/core/plugins/awarding/v3_1/adapters.py, openprocurement/auctions/core/plugins/contracting/v3_1/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/169)
=> common loki type item

openprocurement/auctions/core/tests/plugins/contracting/v2_1/tests/blanks/contract_blanks.py, openprocurement/auctions/core/tests/plugins/contracting/v3_1/tests/blanks/contract_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/168)
depends on https://github.com/openprocurement/openprocurement.api/pull/378
=> Fix tests according to decimal amount

openprocurement/auctions/core/models/roles.py, openprocurement/auctions/core/tests/blanks/auction_blanks.py
It was caused by a typo :disappointed:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/172)
=> tenderAttempts patch bug fix

openprocurement/auctions/core/plugins/transferring/validation.py, openprocurement/auctions/core/plugins/transferring/views/auction.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/171)
=> fix accredetation level

openprocurement/auctions/core/adapters.py, openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/models/schema.py, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/validation.py, openprocurement/auctions/core/views/auctions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/177)
=> geb procedure

openprocurement/auctions/core/plugins/awarding/v3_1/models.py
Make endDate always be working day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/181)
=> Use enhanced calendar days calculation

openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/utils.py, openprocurement/auctions/core/views/auctions.py
add docservice url for no auction test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/182)
=> add same auction post

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/views/auctions.py
The status is added in order to be able to more flexibly define
the initialization according to the status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/183)
=> added arg status to the auction initializator

openprocurement/auctions/core/design.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/184)
=> Add `auctionParameters` to listing fields for auction type detection

openprocurement/auctions/core/models/roles.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/185)
=> Add documents to blacklist in tessel roles

openprocurement/auctions/core/plugins/awarding/v3_1/adapters.py, openprocurement/auctions/core/plugins/awarding/v3_1/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/186)
- Add opportunity to choose status for award if only one bid exist
=> Add configuration to awarding to every procedure can make a little configuration for awarding process

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py
Added manager for working with documents.
It implements the interface of the basic manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/187)
=> added document manager

openprocurement/auctions/core/constants.py, openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/188)
=> Bring generate_rectificationPeriod

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/traversal.py, openprocurement/auctions/core/validation.py
interfaces:
- IItemManager:
for work in views of items
- IAuctionItemer:
sub_manager of auction manager for work with items
- IAuctionChanger:
sub_manager of item manager for work with item changes
- IItemRepresenter:
sub_manager of item manager for work with item representation
- IItemLogger:
sub_manager of item manager for work with item logs
- IAuctionSubResourceItemRepresenter:
for representation of item as
auction sub_resource
- IAuctionSubResourcesRepresenter:
sub_manager of auction manager for work representation of
sub_resources
- IAuctionSubResourcesRepresentersFactory:
factory for auction sub_resource representation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement …
=> add items interfaces

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py
- named validator is for adding as validator to sub-managers
- add save state var for sub-managers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/190)
=> add named validator interface

openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/191)
=> fix generate_rectificationPeriod_period_margin

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/193)
=> add representer for cancellation subresource

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/validation.py, openprocurement/auctions/core/views/auctions.py, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/194)
=> Geb compatibility

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/plugins/awarding/base/adapters.py, openprocurement/auctions/core/plugins/awarding/v3_1/adapters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/195)
=> modify awarding 3_1

openprocurement/auctions/core/managers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/203)
=> add request to bid representer

openprocurement/auctions/core/plugins/awarding/base/views/award_document.py, openprocurement/auctions/core/plugins/awarding/v3_1/adapters.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/206)
=> add validation to access of changing award

openprocurement/auctions/core/plugins/awarding/base/adapters.py, openprocurement/auctions/core/tests/plugins/awarding/v3_1/tests/award.py, openprocurement/auctions/core/tests/plugins/awarding/v3_1/tests/blanks/award_blanks.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/207)
=> fix access to patch award

openprocurement/auctions/core/models/roles.py, openprocurement/auctions/core/tests/base.py, openprocurement/auctions/core/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/210)
=> Changes for appraisal auction

openprocurement/auctions/core/models/schema.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/209)
=> add to cbd2 Item schema_properties

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/views/auctions.py
Reverts openprocurement/openprocurement.auctions.core#213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/216)
=> Revert "geb refactoring"

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/views/auctions.py
Reverts openprocurement/openprocurement.auctions.core#216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/217)
=> geb refactoring

openprocurement/auctions/core/plugins/awarding/v3_1/constants.py, openprocurement/auctions/core/plugins/awarding/v3_1/models.py, openprocurement/auctions/core/plugins/awarding/v3_1/utils.py, openprocurement/auctions/core/tests/plugins/awarding/v3_1/tests/blanks/award_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/219)
=> Add opportunity to configurate awarding 3 1

openprocurement/auctions/core/interfaces.py, openprocurement/auctions/core/managers.py, openprocurement/auctions/core/views/auctions.py
This reverts commit 6ff78be0e8bd83a9e6934e1a76961534d2250041.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/222)
=> Revert "Revert "geb refactoring""

openprocurement/auctions/core/plugins/contracting/v3_1/adapters.py, openprocurement/auctions/core/plugins/contracting/v3_1/extenders.py, openprocurement/auctions/core/plugins/contracting/v3_1/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/221)
=> Move logic from ContractManager to ContractExtender

openprocurement/auctions/core/plugins/contracting/v3_1/adapters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/224)
=> Use content configurator to customize contract logic

openprocurement/auctions/core/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/227)
=> Remove deprecated behaviour

openprocurement/auctions/core/utils.py
depends on https://github.com/openprocurement/openprocurement.api/pull/427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/226)
=> Add import

openprocurement/auctions/core/tests/plugins/awarding/v3_1/tests/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/229)
=> Disable TZ-wontfix bugged tests

openprocurement/auctions/core/tests/plugins/awarding/v2_1/tests/blanks/award_blanks.py, openprocurement/auctions/core/tests/plugins/awarding/v3/tests/blanks/award_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/231)
=> fix timezone in tests

openprocurement/auctions/core/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/232)
=> Add noqa import

openprocurement/auctions/core/plugins/awarding/base/adapters.py, openprocurement/auctions/core/plugins/awarding/v3_1/adapters.py, openprocurement/auctions/core/plugins/awarding/v3_1/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/234)
=> Refactore awarding 3.1 structure

openprocurement/auctions/core/tests/plugins/awarding/v3/tests/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.auctions.core/236)
=> Comment test with TZ problem that appear in certain time
